apiVersion: v1
kind: Service
metadata:
  name: otel-collector-opentelemetry-collector
  namespace: observability
spec:
  selector:
    app.kubernetes.io/name: opentelemetry-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
  type: ClusterIP
