name: CI-CD-Auth-Service

on:
  push:
    branches: [ main ]
    paths: [ 'apps/auth-service/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'apps/auth-service/**' ]

permissions:
  id-token: write
  contents: write 

jobs:
  build-and-test:
    name: Build and SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache-dependency-path: apps/auth-service/go.sum

      - name: Run Trivy SAST
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          scan-ref: './apps/auth-service'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

  docker-ops:
    name: Docker Build and Scan
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Hash do Commit
      - name: Build Image
        run: |
          docker build -t auth-service:${{ github.sha }} ./apps/auth-service
          docker tag auth-service:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/auth-service:${{ github.sha }}

      # Escaneando a imagem com a tag correta
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'auth-service:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'

      # Push da imagem com a tag correta
      - name: Push Image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/auth-service:${{ github.sha }}

      # Atualização automática do GitOps para o ArgoCD
      - name: Update GitOps Repo (ArgoCD)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Troca a tag da imagem no arquivo deployment.yaml pelo hash do commit atual
          sed -i -E "s|(image: .*/auth-service:).*|\1${{ github.sha }}|g" k8s/services/auth/auth-deployment.yaml
          
          git add k8s/services/auth/auth-deployment.yaml
          git commit -m "GitOps: atualizando tag do auth-service para ${{ github.sha }}"
          git push