name: CI-CD-Targeting-Service
on:
  push:
    branches: [ main ]
    paths: [ 'apps/targeting-service/**' ]
permissions:
  id-token: write
  contents: read
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Trivy SAST
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          scan-ref: './apps/targeting-service'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build & Tag
        run: |
          docker build -t targeting-service:latest ./apps/targeting-service
          docker tag targeting-service:latest ${{ steps.login-ecr.outputs.registry }}/targeting-service:latest
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'targeting-service:latest'
          exit-code: '1'
          severity: 'CRITICAL'
      - name: Push Image
        run: docker push ${{ steps.login-ecr.outputs.registry }}/targeting-service:latest